In [1]:
#Pandas Read File - CSV
# Dependencies and Setup
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
# File to Load
file_to_load = "Data/nfl_game_scores.csv"
# Read File and store into Pandas data frame
data = pd.read_csv(file_to_load)

In [2]:
data.shape

(12947, 17)

In [3]:
data.dtypes

schedule_date           object
schedule_season          int64
schedule_week           object
schedule_playoff          bool
team_home               object
score_home             float64
score_away             float64
team_away               object
team_favorite_id        object
spread_favorite        float64
over_under_line         object
stadium                 object
stadium_neutral           bool
weather_temperature    float64
weather_wind_mph       float64
weather_humidity        object
weather_detail          object
dtype: object

In [4]:
data.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
0,9/2/1966,1966,1,False,Miami Dolphins,14.0,23.0,Oakland Raiders,NaN,NaN,NaN,Orange Bowl,False,83.0,6.0,71,NaN
1,9/3/1966,1966,1,False,Houston Oilers,45.0,7.0,Denver Broncos,NaN,NaN,NaN,Rice Stadium,False,81.0,7.0,70,NaN
2,9/4/1966,1966,1,False,San Diego Chargers,27.0,7.0,Buffalo Bills,NaN,NaN,NaN,Balboa Stadium,False,70.0,7.0,82,NaN
3,9/9/1966,1966,2,False,Miami Dolphins,14.0,19.0,New York Jets,NaN,NaN,NaN,Orange Bowl,False,82.0,11.0,78,NaN
4,9/10/1966,1966,1,False,Green Bay Packers,24.0,3.0,Baltimore Colts,NaN,NaN,NaN,Lambeau Field,False,64.0,8.0,62,NaN

In [5]:
#Get last years
last_10y = data[(data['schedule_season'] > 2009)]

In [6]:
last_10y.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
10008,9/9/2010,2010,1,False,New Orleans Saints,14.0,9.0,Minnesota Vikings,NO,-5.0,49.5,Louisiana Superdome,False,72.0,0.0,NaN,DOME
10009,9/12/2010,2010,1,False,Buffalo Bills,10.0,15.0,Miami Dolphins,MIA,-3.0,39,Ralph Wilson Stadium,False,64.0,7.0,81,NaN
10010,9/12/2010,2010,1,False,Chicago Bears,19.0,14.0,Detroit Lions,CHI,-6.5,45,Soldier Field,False,75.0,1.0,45,NaN
10011,9/12/2010,2010,1,False,Houston Texans,34.0,24.0,Indianapolis Colts,IND,-1.0,48,Reliant Stadium,False,89.0,5.0,NaN,DOME (Open Roof)
10012,9/12/2010,2010,1,False,Jacksonville Jaguars,24.0,17.0,Denver Broncos,JAX,-3.0,41.5,EverBank Field,False,91.0,1.0,67,NaN

In [7]:
#Get Stats
last_10y.describe()

,schedule_season,score_home,score_away,spread_favorite,weather_temperature,weather_wind_mph
count,2939.000000,2938.000000,2938.000000,2939.000000,2497.000000,2497.000000
mean,2015.003403,23.909803,21.848877,-5.290915,62.836203,4.591510
std,3.164428,10.290885,9.920160,3.394564,15.423249,4.630642
min,2010.000000,0.000000,0.000000,-26.500000,-6.000000,0.000000
25%,2012.000000,17.000000,15.000000,-7.000000,53.000000,0.000000
50%,2015.000000,24.000000,21.000000,-4.000000,70.000000,4.000000
75%,2018.000000,31.000000,28.000000,-3.000000,72.000000,7.000000
max,2020.000000,62.000000,59.000000,0.000000,97.000000,40.000000

In [9]:
#Create a column with a flag for Local or Visit - Patriots
last_10y['home_or_away'] = np.where(last_10y['team_home'] == 'New England Patriots', 1, 0)

<ipython-input-9-27278d6cc892>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  last_10y['home_or_away'] = np.where(last_10y['team_home'] == 'New England Patriots', 1, 0)

In [10]:
last_10y

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail,home_or_away
10008,9/9/2010,2010,1,False,New Orleans Saints,14.0,9.0,Minnesota Vikings,NO,-5.0,49.5,Louisiana Superdome,False,72.0,0.0,NaN,DOME,0
10009,9/12/2010,2010,1,False,Buffalo Bills,10.0,15.0,Miami Dolphins,MIA,-3.0,39,Ralph Wilson Stadium,False,64.0,7.0,81,NaN,0
10010,9/12/2010,2010,1,False,Chicago Bears,19.0,14.0,Detroit Lions,CHI,-6.5,45,Soldier Field,False,75.0,1.0,45,NaN,0
10011,9/12/2010,2010,1,False,Houston Texans,34.0,24.0,Indianapolis Colts,IND,-1.0,48,Reliant Stadium,False,89.0,5.0,NaN,DOME (Open Roof),0
10012,9/12/2010,2010,1,False,Jacksonville Jaguars,24.0,17.0,Denver Broncos,JAX,-3.0,41.5,EverBank Field,False,91.0,1.0,67,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12942,1/17/2021,2020,Division,True,Kansas City Chiefs,22.0,17.0,Cleveland Browns,KC,-8.0,56,Arrowhead Stadium,False,NaN,NaN,NaN,NaN,0
12943,1/17/2021,2020,Division,True,New Orleans Saints,20.0,30.0,Tampa Bay Buccaneers,NO,-2.5,53,Mercedes-Benz Superdome,False,NaN,NaN,NaN,NaN,0
12944,1/24/2021,2020,Conference,True,Green Bay Packers,26.0,31.0,Tampa Bay Buccaneers,GB,-3.0,53,Lambeau Field,False,NaN,NaN,NaN,NaN,0
12945,1/24/2021,2020,Conference,True,Kansas City Chiefs,38.0,24.0,Buffalo Bills,KC,-3.0,55,Arrowhead Stadium,False,NaN,NaN,NaN,NaN,0
12946,2/7/2021,2020,Superbowl,True,Tampa Bay Buccaneers,NaN,NaN,Kansas City Chiefs,KC,-3.0,56,Raymond James Stadium,False,NaN,NaN,NaN,NaN,0

In [11]:
#Filter for an specific team - Patriots
last_10y_byteam = last_10y.loc[(last_10y["team_home"] == "New England Patriots") | (last_10y["team_away"] == "New England Patriots")]

In [12]:
last_10y_byteam.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail,home_or_away
10013,9/12/2010,2010,1,False,New England Patriots,38.0,24.0,Cincinnati Bengals,NE,-5.5,45,Gillette Stadium,False,63.0,10.0,NaN,NaN,1
10034,9/19/2010,2010,2,False,New York Jets,28.0,14.0,New England Patriots,NE,-3.0,39.5,MetLife Stadium,False,82.0,6.0,36,NaN,0
10049,9/26/2010,2010,3,False,New England Patriots,38.0,30.0,Buffalo Bills,NE,-14.5,43,Gillette Stadium,False,68.0,11.0,NaN,NaN,1
10069,10/4/2010,2010,4,False,Miami Dolphins,14.0,41.0,New England Patriots,NE,-1.0,48,Sun Life Stadium,False,81.0,1.0,60,NaN,0
10089,10/17/2010,2010,6,False,New England Patriots,23.0,20.0,Baltimore Ravens,NE,-3.0,44.5,Gillette Stadium,False,57.0,14.0,NaN,NaN,1

In [13]:
#Select specific columns
final = last_10y_byteam.filter(["team_home","team_away" , "score_home","score_away" ,"weather_temperature", "home_or_away"])

In [14]:
final.head()

,team_home,team_away,score_home,score_away,weather_temperature,home_or_away
10013,New England Patriots,Cincinnati Bengals,38.0,24.0,63.0,1
10034,New York Jets,New England Patriots,28.0,14.0,82.0,0
10049,New England Patriots,Buffalo Bills,38.0,30.0,68.0,1
10069,Miami Dolphins,New England Patriots,14.0,41.0,81.0,0
10089,New England Patriots,Baltimore Ravens,23.0,20.0,57.0,1

In [15]:
#Add new column with score
final['score'] = np.where(final['team_away'] == 'New England Patriots', final['score_away'], final['score_home'])

In [16]:
final.head()

,team_home,team_away,score_home,score_away,weather_temperature,home_or_away,score
10013,New England Patriots,Cincinnati Bengals,38.0,24.0,63.0,1,38.0
10034,New York Jets,New England Patriots,28.0,14.0,82.0,0,14.0
10049,New England Patriots,Buffalo Bills,38.0,30.0,68.0,1,38.0
10069,Miami Dolphins,New England Patriots,14.0,41.0,81.0,0,41.0
10089,New England Patriots,Baltimore Ravens,23.0,20.0,57.0,1,23.0

In [17]:
#Fill blanks in weather with a the mean of column
final = final.fillna(final.mean())

In [18]:
#final.to_excel('final2.xlsx')

In [19]:
final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199 entries, 10013 to 12929
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   team_home            199 non-null    object
 1   team_away            199 non-null    object
 2   score_home           199 non-null    float64
 3   score_away           199 non-null    float64
 4   weather_temperature  199 non-null    float64
 5   home_or_away         199 non-null    int32
 6   score                199 non-null    float64
dtypes: float64(4), int32(1), object(2)
memory usage: 11.7+ KB

In [20]:
final['home_or_away'] = final['home_or_away'].astype('float64')

In [21]:
final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199 entries, 10013 to 12929
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   team_home            199 non-null    object
 1   team_away            199 non-null    object
 2   score_home           199 non-null    float64
 3   score_away           199 non-null    float64
 4   weather_temperature  199 non-null    float64
 5   home_or_away         199 non-null    float64
 6   score                199 non-null    float64
dtypes: float64(5), object(2)
memory usage: 12.4+ KB

In [22]:
#Select data for the model
X = pd.DataFrame(final, columns = ['weather_temperature', 'home_or_away'])
y = pd.DataFrame(final, columns=['score'])

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [24]:
#Build model
lin_reg_mod = LinearRegression()
lin_reg_mod.fit(X_train, y_train)
pred = lin_reg_mod.predict(X_test)

In [25]:
#Calculate the R2_Score between the actual and prediction
test_set_r2 = r2_score(y_test, pred)
#Check if it is closer to 1
print(test_set_r2)

-0.0402187565419303

In [26]:
df_results = y_test
df_results['Predicted'] = pred
df_results['Residuals'] = abs(df_results['score']) - abs(df_results['Predicted'])
print(df_results)

       score  Predicted  Residuals
12568   17.0  27.039430 -10.039430
10612   31.0  30.725462   0.274538
10539   23.0  30.647101  -7.647101
11342   28.0  29.750818  -1.750818
12141   24.0  31.050344  -7.050344
12668   13.0  30.647101 -17.647101
11425   34.0  26.143147   7.856853
10089   23.0  30.563022  -7.563022
10481   34.0  27.875849   6.124151
12436   43.0  27.039430  15.960570
10807   13.0  30.647101 -17.647101
10299   35.0  30.238140   4.761860
10199   45.0  32.133283  12.866717
12377   24.0  31.483519  -7.483519
12155   27.0  30.292287  -3.292287
11747   24.0  31.212785  -7.212785
11578   20.0  27.009498  -7.009498
10541   17.0  29.750818 -12.750818
11635   31.0  29.425936   1.574064
10875    6.0  26.034853 -20.034853
10789   28.0  32.133283  -4.133283
10271   21.0  30.647101  -9.647101
10681   37.0  30.183993   6.816007
11385   51.0  29.859112  21.140888
10507   27.0  31.916695  -4.916695
12706   30.0  27.039430   2.960570
10576   30.0  26.413882   3.586118
10459   31.0  30.725462   0.274538
12489   35.0  30.647101   4.352899
10445   38.0  26.630470  11.369530
10727   23.0  25.818266  -2.818266
12408   37.0  29.012935   7.987065
10895   30.0  30.454728  -0.454728
12126   26.0  32.945487  -6.945487
12166   20.0  24.789474  -4.789474
11827   16.0  28.579759 -12.579759
12013   41.0  27.442674  13.557326
12579   13.0  30.647101 -17.647101
11167   27.0  30.238140  -3.238140
11767   30.0  26.738763   3.261237
11604   27.0  31.591813  -4.591813
11596   10.0  25.818266 -15.818266
10848   23.0  29.750818  -6.750818
10234   34.0  28.850494   5.149506
11675   33.0  26.955351   6.044649
10307   31.0  25.655825   5.344175
11099   30.0  26.522176   3.477824
10593   52.0  26.738763  25.261237
11940   19.0  25.926560  -6.926560
11843   41.0  31.483519   9.516481

<ipython-input-26-c4f80a072444>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_results['Predicted'] = pred
<ipython-input-26-c4f80a072444>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_results['Residuals'] = abs(df_results['score']) - abs(df_results['Predicted'])